
version: '3.7'
services:

  #############################################################################################
  ###                                 SPLUNK DEV BOX                                        ###
  #############################################################################################
  ntt-data-notification-splunk:
    image: splunk/splunk:latest
    environment:
      - SPLUNK_PASSWORD=TestTest
      - SPLUNK_START_ARGS=--accept-license
    ports:
      - "7000:8000"
      - "8088:8088"
    networks:
      notification-net:
        ipv4_address: 172.20.0.5

  #############################################################################################
  ###                            NTT Data notification service                              ###
  #############################################################################################
  ntt-data-notification-service:
    build:
      context: .
      args:
        - SERVICE_NAME=ntt-data-notification-service
    ports:
      - "7080:8080"
    environment:
      - TOKENS=${TOKENS}
      - UPDATE_CARD_BASE=${UPDATE_CARD_BASE}
    networks:
      notification-net:
        ipv4_address: 172.20.0.6

networks: 
  notification-net:
    driver: "bridge"
    ipam:
      config:
        - subnet: 172.20.0.0/24
